name: JueJinEvents

on:
 # schedule:
 #  - cron: "0 10 * * 5"
  
 workflow_dispatch:

env:
 TZ: Asia/Shanghai

jobs:
 JueJinEvents:
  runs-on: ubuntu-latest
  steps:
   - name: Show server date
     run: date
   - name: Checkout Repository
     uses: actions/checkout@v4.1.7
     with:
      sparse-checkout: |
       JueJinEvent
      sparse-checkout-cone-mode: false
   - name: Setup Go environment
     uses: actions/setup-go@v5
     with:
      go-version: '1.22.5'
   - name: Build App 
     working-directory: ./JueJinEvent
     run: go build -o app -ldflags "-w -s" main.go 
   - name: Check Dir
     working-directory: ./JueJinEvent
     run: /bin/ls -l
   - name: Run spider get JueJinEvents\
     working-directory: ./JueJinEvent
     run: ./app
     env:
      Days: "30"
      Aid: "2608"
      COOKIE: ${{ secrets.COOKIE }}
      TOKEN: ${{ secrets.X_SECSDK_CSRF_TOKEN }}
      SECRET: ${{ secrets.SECRET}}
