name: JueJinEvents

on:
 workflow_dispatch:

env:
 TZ: Asia/Shanghai

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   # - name: Checkout Repository
   #   uses: actions/checkout@v4.1.7
   - name: Check Env
     run: echo "${{ vars.COOKIE }} ${{ vars.X_SECSDK_CSRF_TOKEN }}"
   # - name: Run spider get JueJinEvents
   #   run: /bin/bash JueJinEvent 
   #   env:
   #    JUEJIN_COOKIES: 
