name: JueJinEvents

on:
 workflow_dispatch:

env:
 TZ: Asia/Shanghai
 BODY: '{"from_date":"2024-06-30","days":30,"aid":2608}'
 COOKIE: ${{ vars.COOKIE }}
 TOKEN: ${{ vars.X_SECSDK_CSRF_TOKEN }}

jobs:
 JueJinEvents:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repository
     uses: actions/checkout@v4.1.7
     with:
      sparse-checkout: |
       JueJinEvent
      sparse-checkout-cone-mode: false
   - name: Setup Go environment
     uses: actions/setup-go@v5
     with:
      go-version: '1.22.5'
   - name: Build App 
     working-directory: ./JueJinEvent
     run: go build -o app -ldflags "-w -s" main.go 
   - name: Check Dir
     working-directory: ./JueJinEvent
     run: /bin/ls -l
   - name: Run spider get JueJinEvents\
     working-directory: ./JueJinEvent
     run: ./app
