name: 'Auto Issues'

env:
  TZ: Asia/Shanghai

on: issues
jobs:
  Get:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.issue.number == 7
    steps:
    - name: watch issue context
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue body: ${{ github.event.issue.body }}"
    - name: pull readme.md file
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false
    - name: write readme.md file
      run: echo "${{ github.event.issue.body }}" > README.md
    - name: push readme.md file
      run: |
        echo "${{ github.event.issue.body }}" > README.md
        git config user.name [bot]github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[bot]github action issues"
        git push


# 删除不是作者发布Issues
  # Delete:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   if: ${{ github.event.issue.author.name == 'redcrazyghost' }}
    

