name: 'Auto Issues'

env:
  TZ: Asia/Shanghai

on: issues
jobs:
  Get:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.issue.number == 7
    steps:
    - name: View issue information
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue body: ${{ github.event.issue.body }}"
    - name: check file 
      run: |
        "${{ github.event.issue.body }}" > readme.md
        git config user.name [bot]github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[bot]github action issues"
        git push

    # 修改文件readme.md 然后push到仓库
    # - uses: actions/checkout@v3
    # - run: |
    #     git config --global user.email "bot@redcrazyghost.vip"
    #     git config --global user.name "[bot]"

# 删除不是作者发布Issues
  # Delete:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   if: ${{ github.event.issue.author.name == 'redcrazyghost' }}
    

